services:
  influxdb:
    image: influxdb:2.7 # Use the latest 2.x version
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=network_stats
      - INFLUXD_HTTP_AUTH_ENABLED=true

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    ports:
      - "6653:6653"
      - "8080:8080"
    networks:
      - se4as_network
    deploy:
      resources:
        limits:
          memory: "0"
          cpus: "0"

  execute:
    build:
      context: ./execute
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - influxdb
    ports:
      - "5002:5002"
    networks:
      - se4as_network

  plan:
    build:
      context: ./plan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "5001:5001"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_BUCKET=network_stats
      - INFLUXDB_ORG=my-org
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin123
    networks:
      - se4as_network

  analyze:
    build:
      context: ./analyze
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "5004:5004"
    networks:
      - se4as_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
      
volumes:
  influxdb_data: